// <auto-generated />
namespace TesteMicroUniverso.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class inclusao_tabelas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inclusao_tabelas));
        
        string IMigrationMetadata.Id
        {
            get { return "202307310119072_inclusao_tabelas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
